version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
disable_rollback = true
stack_name = "uni-prop-local-web"
s3_prefix = "uni-prop-local-web"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"Local\""
resolve_s3 = true
resolve_image_repositories = true

[default.delete]
[default.delete.parameters]
stack_name = "uni-prop-local-web"
no_prompts = true
