version = 0.1

[default.global.parameters]
stack_name = "uni-prop-local-web"
s3_prefix = "uni-prop-local-web"
resolve_s3 = true
resolve_image_repositories = true

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
disable_rollback = true
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
parameter_overrides = ["Stage=local"]

[default.validate.parameters]
lint = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER" 

# ############################################## #

[dev]
[dev.global]
[dev.global.parameters]
stack_name = "uni-prop-dev-web"
s3_prefix = "uni-prop-dev-web"
resolve_s3 = true
resolve_image_repositories = true

[dev.deploy]
[dev.deploy.parameters]
template = ".aws-sam/packaged-dev-web-service.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=dev"

# ############################################## #

[prod]
[prod.global]
[prod.global.parameters]
stack_name = "uni-prop-prod-web"
s3_prefix = "uni-prop-prod-web"
resolve_s3 = true
resolve_image_repositories = true

[prod.deploy]
[prod.deploy.parameters]
template = ".aws-sam/packaged-prod-web-service.yaml"
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "Stage=prod"